### PR TITLE
Fix docstrings

### PR DESCRIPTION
**Pull request by pitmonticone**
Hi @goedman, just fixed a few typos in the docstrings.

### CODE REVIEW

**Comment by goedman** [comment]
Thanks again Pietro!

**Comment by pitmonticone** [comment]
You're welcome. Let me know if you want me to join the organization with "write access" so that you don't even need to review such minor changes.

**Comment by goedman** [comment]
Hi Pietro,

Just did! Selected owner so you can make modifications, merge, etc.

What is your primary interest? I’m asking this because pretty much all my time is going into the DAG stuff so I feel as if I’m dropping the ball a bit on revising the later chapter notebooks. And these days mainly on SR2StanPluto.jl and StanNotebookExamples.jl.

Thanks for your help!

Rob

Rob J Goedman
***@***.***

**Comment by pitmonticone** [comment]
Hi Rob, thank you for the invitation. 

I'll start the focused reading of the textbook in a few months... so don't worry about that. It's not at all a priority for me.

**Pull request merged**
